title: Francesco Paraggio
description: >
  Full Stack AI Engineer  
  ğŸ“ Piazza Duomo 3, 84067 Santa Marina (SA), Italy  
  ğŸ“§ francesco at greendata.solutions  
  VAT N. IT06083470655

theme: jekyll-theme-minimal
logo: logo.svg
show_downloads: false

github:
  is_project_page: false
